/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FotoTokenRouteImport } from './routes/foto.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRegrasRouteImport } from './routes/_authenticated/regras'
import { Route as AuthenticatedIdentitiesRouteImport } from './routes/_authenticated/identities'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedCamposPersonalizadosRouteImport } from './routes/_authenticated/campos-personalizados'
import { Route as AuthenticatedCamposDoSiteRouteImport } from './routes/_authenticated/campos-do-site'
import { Route as AuthenticatedCampanhasFotoRouteImport } from './routes/_authenticated/campanhas-foto'
import { Route as AuthenticatedBrandingRouteImport } from './routes/_authenticated/branding'
import { Route as AuthenticatedApelidosRouteImport } from './routes/_authenticated/apelidos'
import { Route as AuthenticatedVisitasIndexRouteImport } from './routes/_authenticated/visitas.index'
import { Route as AuthenticatedTerceirizadosIndexRouteImport } from './routes/_authenticated/terceirizados.index'
import { Route as AuthenticatedIdentitiesIndexRouteImport } from './routes/_authenticated/identities.index'
import { Route as AuthenticatedVisitasNovaRouteImport } from './routes/_authenticated/visitas.nova'
import { Route as AuthenticatedTerceirizadosIdRouteImport } from './routes/_authenticated/terceirizados.$id'
import { Route as AuthenticatedIdentitiesNewRouteImport } from './routes/_authenticated/identities.new'
import { Route as AuthenticatedIdentitiesIdRouteImport } from './routes/_authenticated/identities.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoTokenRoute = FotoTokenRouteImport.update({
  id: '/foto/$token',
  path: '/foto/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegrasRoute = AuthenticatedRegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdentitiesRoute = AuthenticatedIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCamposPersonalizadosRoute =
  AuthenticatedCamposPersonalizadosRouteImport.update({
    id: '/campos-personalizados',
    path: '/campos-personalizados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCamposDoSiteRoute =
  AuthenticatedCamposDoSiteRouteImport.update({
    id: '/campos-do-site',
    path: '/campos-do-site',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampanhasFotoRoute =
  AuthenticatedCampanhasFotoRouteImport.update({
    id: '/campanhas-foto',
    path: '/campanhas-foto',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandingRoute = AuthenticatedBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApelidosRoute = AuthenticatedApelidosRouteImport.update({
  id: '/apelidos',
  path: '/apelidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitasIndexRoute =
  AuthenticatedVisitasIndexRouteImport.update({
    id: '/visitas/',
    path: '/visitas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTerceirizadosIndexRoute =
  AuthenticatedTerceirizadosIndexRouteImport.update({
    id: '/terceirizados/',
    path: '/terceirizados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentitiesIndexRoute =
  AuthenticatedIdentitiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIdentitiesRoute,
  } as any)
const AuthenticatedVisitasNovaRoute =
  AuthenticatedVisitasNovaRouteImport.update({
    id: '/visitas/nova',
    path: '/visitas/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTerceirizadosIdRoute =
  AuthenticatedTerceirizadosIdRouteImport.update({
    id: '/terceirizados/$id',
    path: '/terceirizados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdentitiesNewRoute =
  AuthenticatedIdentitiesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedIdentitiesRoute,
  } as any)
const AuthenticatedIdentitiesIdRoute =
  AuthenticatedIdentitiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedIdentitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apelidos': typeof AuthenticatedApelidosRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/campanhas-foto': typeof AuthenticatedCampanhasFotoRoute
  '/campos-do-site': typeof AuthenticatedCamposDoSiteRoute
  '/campos-personalizados': typeof AuthenticatedCamposPersonalizadosRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/identities': typeof AuthenticatedIdentitiesRouteWithChildren
  '/regras': typeof AuthenticatedRegrasRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/foto/$token': typeof FotoTokenRoute
  '/identities/$id': typeof AuthenticatedIdentitiesIdRoute
  '/identities/new': typeof AuthenticatedIdentitiesNewRoute
  '/terceirizados/$id': typeof AuthenticatedTerceirizadosIdRoute
  '/visitas/nova': typeof AuthenticatedVisitasNovaRoute
  '/identities/': typeof AuthenticatedIdentitiesIndexRoute
  '/terceirizados/': typeof AuthenticatedTerceirizadosIndexRoute
  '/visitas/': typeof AuthenticatedVisitasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apelidos': typeof AuthenticatedApelidosRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/campanhas-foto': typeof AuthenticatedCampanhasFotoRoute
  '/campos-do-site': typeof AuthenticatedCamposDoSiteRoute
  '/campos-personalizados': typeof AuthenticatedCamposPersonalizadosRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/regras': typeof AuthenticatedRegrasRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/foto/$token': typeof FotoTokenRoute
  '/identities/$id': typeof AuthenticatedIdentitiesIdRoute
  '/identities/new': typeof AuthenticatedIdentitiesNewRoute
  '/terceirizados/$id': typeof AuthenticatedTerceirizadosIdRoute
  '/visitas/nova': typeof AuthenticatedVisitasNovaRoute
  '/identities': typeof AuthenticatedIdentitiesIndexRoute
  '/terceirizados': typeof AuthenticatedTerceirizadosIndexRoute
  '/visitas': typeof AuthenticatedVisitasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/apelidos': typeof AuthenticatedApelidosRoute
  '/_authenticated/branding': typeof AuthenticatedBrandingRoute
  '/_authenticated/campanhas-foto': typeof AuthenticatedCampanhasFotoRoute
  '/_authenticated/campos-do-site': typeof AuthenticatedCamposDoSiteRoute
  '/_authenticated/campos-personalizados': typeof AuthenticatedCamposPersonalizadosRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/identities': typeof AuthenticatedIdentitiesRouteWithChildren
  '/_authenticated/regras': typeof AuthenticatedRegrasRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/foto/$token': typeof FotoTokenRoute
  '/_authenticated/identities/$id': typeof AuthenticatedIdentitiesIdRoute
  '/_authenticated/identities/new': typeof AuthenticatedIdentitiesNewRoute
  '/_authenticated/terceirizados/$id': typeof AuthenticatedTerceirizadosIdRoute
  '/_authenticated/visitas/nova': typeof AuthenticatedVisitasNovaRoute
  '/_authenticated/identities/': typeof AuthenticatedIdentitiesIndexRoute
  '/_authenticated/terceirizados/': typeof AuthenticatedTerceirizadosIndexRoute
  '/_authenticated/visitas/': typeof AuthenticatedVisitasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apelidos'
    | '/branding'
    | '/campanhas-foto'
    | '/campos-do-site'
    | '/campos-personalizados'
    | '/diagnostics'
    | '/empresas'
    | '/identities'
    | '/regras'
    | '/settings'
    | '/foto/$token'
    | '/identities/$id'
    | '/identities/new'
    | '/terceirizados/$id'
    | '/visitas/nova'
    | '/identities/'
    | '/terceirizados/'
    | '/visitas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apelidos'
    | '/branding'
    | '/campanhas-foto'
    | '/campos-do-site'
    | '/campos-personalizados'
    | '/diagnostics'
    | '/empresas'
    | '/regras'
    | '/settings'
    | '/foto/$token'
    | '/identities/$id'
    | '/identities/new'
    | '/terceirizados/$id'
    | '/visitas/nova'
    | '/identities'
    | '/terceirizados'
    | '/visitas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/apelidos'
    | '/_authenticated/branding'
    | '/_authenticated/campanhas-foto'
    | '/_authenticated/campos-do-site'
    | '/_authenticated/campos-personalizados'
    | '/_authenticated/diagnostics'
    | '/_authenticated/empresas'
    | '/_authenticated/identities'
    | '/_authenticated/regras'
    | '/_authenticated/settings'
    | '/foto/$token'
    | '/_authenticated/identities/$id'
    | '/_authenticated/identities/new'
    | '/_authenticated/terceirizados/$id'
    | '/_authenticated/visitas/nova'
    | '/_authenticated/identities/'
    | '/_authenticated/terceirizados/'
    | '/_authenticated/visitas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  FotoTokenRoute: typeof FotoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto/$token': {
      id: '/foto/$token'
      path: '/foto/$token'
      fullPath: '/foto/$token'
      preLoaderRoute: typeof FotoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regras': {
      id: '/_authenticated/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof AuthenticatedRegrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identities': {
      id: '/_authenticated/identities'
      path: '/identities'
      fullPath: '/identities'
      preLoaderRoute: typeof AuthenticatedIdentitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campos-personalizados': {
      id: '/_authenticated/campos-personalizados'
      path: '/campos-personalizados'
      fullPath: '/campos-personalizados'
      preLoaderRoute: typeof AuthenticatedCamposPersonalizadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campos-do-site': {
      id: '/_authenticated/campos-do-site'
      path: '/campos-do-site'
      fullPath: '/campos-do-site'
      preLoaderRoute: typeof AuthenticatedCamposDoSiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campanhas-foto': {
      id: '/_authenticated/campanhas-foto'
      path: '/campanhas-foto'
      fullPath: '/campanhas-foto'
      preLoaderRoute: typeof AuthenticatedCampanhasFotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branding': {
      id: '/_authenticated/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AuthenticatedBrandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apelidos': {
      id: '/_authenticated/apelidos'
      path: '/apelidos'
      fullPath: '/apelidos'
      preLoaderRoute: typeof AuthenticatedApelidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visitas/': {
      id: '/_authenticated/visitas/'
      path: '/visitas'
      fullPath: '/visitas/'
      preLoaderRoute: typeof AuthenticatedVisitasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terceirizados/': {
      id: '/_authenticated/terceirizados/'
      path: '/terceirizados'
      fullPath: '/terceirizados/'
      preLoaderRoute: typeof AuthenticatedTerceirizadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identities/': {
      id: '/_authenticated/identities/'
      path: '/'
      fullPath: '/identities/'
      preLoaderRoute: typeof AuthenticatedIdentitiesIndexRouteImport
      parentRoute: typeof AuthenticatedIdentitiesRoute
    }
    '/_authenticated/visitas/nova': {
      id: '/_authenticated/visitas/nova'
      path: '/visitas/nova'
      fullPath: '/visitas/nova'
      preLoaderRoute: typeof AuthenticatedVisitasNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/terceirizados/$id': {
      id: '/_authenticated/terceirizados/$id'
      path: '/terceirizados/$id'
      fullPath: '/terceirizados/$id'
      preLoaderRoute: typeof AuthenticatedTerceirizadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identities/new': {
      id: '/_authenticated/identities/new'
      path: '/new'
      fullPath: '/identities/new'
      preLoaderRoute: typeof AuthenticatedIdentitiesNewRouteImport
      parentRoute: typeof AuthenticatedIdentitiesRoute
    }
    '/_authenticated/identities/$id': {
      id: '/_authenticated/identities/$id'
      path: '/$id'
      fullPath: '/identities/$id'
      preLoaderRoute: typeof AuthenticatedIdentitiesIdRouteImport
      parentRoute: typeof AuthenticatedIdentitiesRoute
    }
  }
}

interface AuthenticatedIdentitiesRouteChildren {
  AuthenticatedIdentitiesIdRoute: typeof AuthenticatedIdentitiesIdRoute
  AuthenticatedIdentitiesNewRoute: typeof AuthenticatedIdentitiesNewRoute
  AuthenticatedIdentitiesIndexRoute: typeof AuthenticatedIdentitiesIndexRoute
}

const AuthenticatedIdentitiesRouteChildren: AuthenticatedIdentitiesRouteChildren =
  {
    AuthenticatedIdentitiesIdRoute: AuthenticatedIdentitiesIdRoute,
    AuthenticatedIdentitiesNewRoute: AuthenticatedIdentitiesNewRoute,
    AuthenticatedIdentitiesIndexRoute: AuthenticatedIdentitiesIndexRoute,
  }

const AuthenticatedIdentitiesRouteWithChildren =
  AuthenticatedIdentitiesRoute._addFileChildren(
    AuthenticatedIdentitiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApelidosRoute: typeof AuthenticatedApelidosRoute
  AuthenticatedBrandingRoute: typeof AuthenticatedBrandingRoute
  AuthenticatedCampanhasFotoRoute: typeof AuthenticatedCampanhasFotoRoute
  AuthenticatedCamposDoSiteRoute: typeof AuthenticatedCamposDoSiteRoute
  AuthenticatedCamposPersonalizadosRoute: typeof AuthenticatedCamposPersonalizadosRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedIdentitiesRoute: typeof AuthenticatedIdentitiesRouteWithChildren
  AuthenticatedRegrasRoute: typeof AuthenticatedRegrasRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTerceirizadosIdRoute: typeof AuthenticatedTerceirizadosIdRoute
  AuthenticatedVisitasNovaRoute: typeof AuthenticatedVisitasNovaRoute
  AuthenticatedTerceirizadosIndexRoute: typeof AuthenticatedTerceirizadosIndexRoute
  AuthenticatedVisitasIndexRoute: typeof AuthenticatedVisitasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApelidosRoute: AuthenticatedApelidosRoute,
  AuthenticatedBrandingRoute: AuthenticatedBrandingRoute,
  AuthenticatedCampanhasFotoRoute: AuthenticatedCampanhasFotoRoute,
  AuthenticatedCamposDoSiteRoute: AuthenticatedCamposDoSiteRoute,
  AuthenticatedCamposPersonalizadosRoute:
    AuthenticatedCamposPersonalizadosRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedIdentitiesRoute: AuthenticatedIdentitiesRouteWithChildren,
  AuthenticatedRegrasRoute: AuthenticatedRegrasRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTerceirizadosIdRoute: AuthenticatedTerceirizadosIdRoute,
  AuthenticatedVisitasNovaRoute: AuthenticatedVisitasNovaRoute,
  AuthenticatedTerceirizadosIndexRoute: AuthenticatedTerceirizadosIndexRoute,
  AuthenticatedVisitasIndexRoute: AuthenticatedVisitasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  FotoTokenRoute: FotoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
